export const catalogConstants = {
  development: {
    MAIN_MENU_CATEGORY_ID: 'HQ5TKLSWGC5QRT4MXI5OM2AO',
    SPECIALS_CATEGORY_ID: '3Z4YSZEJONV77YDQEBCYMD46',
  },
  production: {
    MAIN_MENU_CATEGORY_ID: 'HQ5TKLSWGC5QRT4MXI5OM2AO',
    SPECIALS_CATEGORY_ID: '3Z4YSZEJONV77YDQEBCYMD46',
  },
};
