export const catalogConstants = {
  development: {
    MAIN_MENU_CATEGORY_ID: 'SJDDUACDLVPRP66BCCIMKNLV',
    SPECIALS_CATEGORY_ID: '6KLNTZHSVIAF6GXI2QDBNJN2',
  },
  production: {
    MAIN_MENU_CATEGORY_ID: 'KIL4Q5STYZAPP2G5YFLVM2ON',
    SPECIALS_CATEGORY_ID: '5TLKXFOFFITNTF5XXIGVPKPB',
  },
};
