require('dotenv').config();

export const environments = {
  development: {
    SQUARE_APP_ID: process.env.SQUARE_APP_ID_DEV,
    SQUARE_LOCATION_ID: process.env.SQUARE_LOCATION_ID_DEV,
    SQUARE_ACCESS_TOKEN: process.env.SQUARE_ACCESS_TOKEN_DEV,
    GMAIL_CLIENT_ID: process.env.GMAIL_CLIENT_ID_DEV,
    GMAIL_CLIENT_SECRET: process.env.GMAIL_CLIENT_SECRET_DEV,
    GMAIL_OAUTH_REDIRECT_URI: process.env.GMAIL_OAUTH_REDIRECT_URI,
    GMAIL_OAUTH_REFRESH_TOKEN: process.env.GMAIL_OAUTH_REFRESH_TOKEN_DEV,
    SONRISA_EMAIL: process.env.SONRISA_EMAIL_DEV,
    INSTAGRAM_TOKEN: process.env.INSTAGRAM_TOKEN_DEV,
  },
  production: {
    SQUARE_APP_ID: process.env.SQUARE_APP_ID_PROD,
    SQUARE_LOCATION_ID: process.env.SQUARE_LOCATION_ID_PROD,
    SQUARE_ACCESS_TOKEN: process.env.SQUARE_ACCESS_TOKEN_PROD,
    GMAIL_CLIENT_ID: process.env.GMAIL_CLIENT_ID_PROD,
    GMAIL_CLIENT_SECRET: process.env.GMAIL_CLIENT_SECRET_PROD,
    GMAIL_OAUTH_REDIRECT_URI: process.env.GMAIL_OAUTH_REDIRECT_URI,
    GMAIL_OAUTH_REFRESH_TOKEN: process.env.GMAIL_OAUTH_REFRESH_TOKEN_PROD,
    SONRISA_EMAIL: process.env.SONRISA_EMAIL_PROD,
    INSTAGRAM_TOKEN: process.env.INSTAGRAM_TOKEN_DEV,
  },
  test: {
    SQUARE_APP_ID: process.env.SQUARE_APP_ID_DEV,
    SQUARE_LOCATION_ID: process.env.SQUARE_LOCATION_ID_DEV,
    SQUARE_ACCESS_TOKEN: process.env.SQUARE_ACCESS_TOKEN_DEV,
    GMAIL_CLIENT_ID: process.env.GMAIL_CLIENT_ID_DEV,
    GMAIL_CLIENT_SECRET: process.env.GMAIL_CLIENT_SECRET_DEV,
    GMAIL_OAUTH_REDIRECT_URI: process.env.GMAIL_OAUTH_REDIRECT_URI,
    GMAIL_OAUTH_REFRESH_TOKEN: process.env.GMAIL_OAUTH_REFRESH_TOKEN_DEV,
    SONRISA_EMAIL: process.env.SONRISA_EMAIL_DEV,
    INSTAGRAM_TOKEN: process.env.INSTAGRAM_TOKEN_DEV,
  },
};
