import { Schema } from '../schema';
import { Address } from './address';
/**
 * Represents the payment details of a card to be used for payments. These
 * details are determined by the payment token generated by Web Payments SDK.
 */
export interface Card {
  /** Unique ID for this card. Generated by Square. */
  id?: string;
  /** Indicates a card's brand, such as `VISA` or `MASTERCARD`. */
  card_brand?: string;
  /** The last 4 digits of the card number. */
  last_4?: string;
  /** The expiration month of the associated card as an integer between 1 and 12. */
  exp_month?: bigint;
  /** The four-digit year of the card's expiration date. */
  exp_year?: bigint;
  /** The name of the cardholder. */
  cardholder_name?: string;
  /** Represents a physical address. */
  billing_address?: Address;
  /**
   * __Not currently set.__ Intended as a Square-assigned identifier, based
   * on the card number, to identify the card across multiple locations within a
   * single application.
   */
  fingerprint?: string;
  /** The ID of a customer created using the Customers API to be associated with the card. */
  customer_id?: string;
  /**
   * An optional user-defined reference ID that associates this card with
   * another entity in an external system. For example, a customer ID from an
   * external customer management system.
   */
  reference_id?: string;
  /** Indicates whether or not a card can be used for payments. */
  enabled?: boolean;
  /** Indicates a card's type, such as `CREDIT` or `DEBIT`. */
  card_type?: string;
  /** Indicates a card's prepaid type, such as `NOT_PREPAID` or `PREPAID`. */
  prepaid_type?: string;
  /**
   * The first six digits of the card number, known as the Bank Identification Number (BIN). Only the Payments API
   * returns this field.
   */
  bin?: string;
  /**
   * Current version number of the card. Increments with each card update. Requests to update an
   * existing Card object will be rejected unless the version in the request matches the current
   * version for the Card.
   */
  version?: bigint;
}
export declare const cardSchema: Schema<Card>;
